### ISSUE TITLE
keep crashing

### ISSUE THREAD

**Issue by zh99998** [smparkes/kibosh#1]
first i get

``` ruby
undefined method `detect' for nil:NilClass
D:/Ruby200/lib/ruby/gems/2.0.0/gems/kibosh-0.1.0/lib/kibosh/router.rb:14:in `driver'
```

and i added hosts to Kibosh init

```
  def initialize options = {hosts: {'my-card.in' => 'chat.my-card.in'}}
    @router = Router.new options[:hosts]
  end
```

then i get 

```
<body xmlns="http://jabber.org/protocol/httpbind" xmlns:xmpp="urn:xmpp:xbosh" rid="11407089" to="my-card.in" xml:lang="e
n" wait="60" hold="1" content="text/xml; charset=utf-8" ver="1.6" xmpp:version="1.0"/>
[ defer
Unexpected error while processing request: Status must be >=100 seen as integer
        D:/Ruby200/lib/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/lint.rb:20:in `assert'
        D:/Ruby200/lib/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/lint.rb:555:in `check_status'
        D:/Ruby200/lib/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/lint.rb:51:in `_call'
        D:/Ruby200/lib/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/lint.rb:37:in `call'
        D:/Ruby200/lib/ruby/gems/2.0.0/gems/thin-1.6.0/lib/thin/connection.rb:82:in `block in pre_process'
        D:/Ruby200/lib/ruby/gems/2.0.0/gems/thin-1.6.0/lib/thin/connection.rb:80:in `catch'
        D:/Ruby200/lib/ruby/gems/2.0.0/gems/thin-1.6.0/lib/thin/connection.rb:80:in `pre_process'
        D:/Ruby200/lib/ruby/gems/2.0.0/gems/thin-1.6.0/lib/thin/connection.rb:55:in `process'
        D:/Ruby200/lib/ruby/gems/2.0.0/gems/thin-1.6.0/lib/thin/connection.rb:41:in `receive_data'
        D:/Ruby200/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3-x86-mingw32/lib/eventmachine.rb:187:in `run_machine'
        D:/Ruby200/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3-x86-mingw32/lib/eventmachine.rb:187:in `run'
        D:/Ruby200/lib/ruby/gems/2.0.0/gems/thin-1.6.0/lib/thin/backends/base.rb:73:in `start'
        D:/Ruby200/lib/ruby/gems/2.0.0/gems/thin-1.6.0/lib/thin/server.rb:162:in `start'
        D:/Ruby200/lib/ruby/gems/2.0.0/gems/thin-1.6.0/lib/thin/controllers/controller.rb:87:in `start'
        D:/Ruby200/lib/ruby/gems/2.0.0/gems/thin-1.6.0/lib/thin/runner.rb:204:in `run_command'
        D:/Ruby200/lib/ruby/gems/2.0.0/gems/thin-1.6.0/lib/thin/runner.rb:156:in `run!'
        ./bin/kibosh:12:in `<main>'

> (prefix) <?xml version="1.0"?>
```

well..don't know how to fix..

**Comment by zh99998** [comment]
closing this since long time inactive
